### ISSUE TITLE
How to generate the VRF key is unknown.

### ISSUE THREAD

**Issue by GodTanu** [nemtech/symbol-docs#529] opened 2020-11-02 08:21 UTC
**Describe the error**
A clear and concise description of what the error is.

How to generate the VRF key is unknown.

**To Reproduce**

https://docs.symbolplatform.com/guides/accountlink/activating-delegated-harvesting.html

Suddenly, the VRF key entry appears.
But nowhere in the document is there a way to generate it.
It's not even clear if the tool exists.

**Expected behavior**

Added a note on how to generate VRF keys.

**Comment by segfaultxavi** [comment] 2020-11-02 09:30
Duplicate of #468.

Thanks for the report! I'm working on this right now.

**Closed** 2020-11-02 09:29 UTC
Labels: bug

**Comment by GodTanu** [comment] 2020-11-02 14:23
Can you tell me the procedure?

**Comment by segfaultxavi** [comment] 2020-11-02 14:38
Basically, you now also need to register [VRF](https://docs.symbolplatform.com/serialization/coresystem.html#vrf-key-link) and [Node](https://docs.symbolplatform.com/serialization/account_link.html#node-key-link) Keys before sending the PersistentDelegationRequestTransaction.
The VRF is similar to a regular account, you can create it with `symbol-cli account generate`. So, in summary:
```
symbol-cli transaction accountkeylink --linked-public-key <REMOTE_ACCOUNT_PUBLIC_KEY> --action Link --sync
symbol-cli transaction vrfkeylink --linked-public-key <VRF_PUBLIC_KEY> --action Link --sync
symbol-cli transaction nodekeylink --linked-public-key <NODE_PUBLIC_KEY> --action Link --sync
symbol-cli transaction persistentharvestdelegation --remote-private-key <REMOTE_PRIVATE_KEY> --recipient-public-key <NODE_PUBLIC_KEY> --vrf-private-key <VRF_PRIVATE_KEY> --sync
```

**Comment by GodTanu** [comment] 2020-11-03 00:55
There is no mention of nodekeylink in the documentation.  

Is this necessary for delegate harvesting?

**Comment by segfaultxavi** [comment] 2020-11-03 08:22
> Is this necessary for delegate harvesting?

It is necessary, and it is being added to the docs.

**Comment by GodTanu** [comment] 2020-11-03 13:00
Please explain briefly now.  
I'm confused because I don't know the procedure.

please.

**Comment by segfaultxavi** [comment] 2020-11-05 17:39
The new docs are now under review in #531.
You can see a preview here:
https://deploy-preview-531--nemtech.netlify.app/concepts/harvesting.html
https://deploy-preview-531--nemtech.netlify.app/guides/accountlink/activating-delegated-harvesting.html

Feel free to comment in #531!
