### ISSUE TITLE
[Guide] Supernode setup using bootstrap

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-docs#566] opened 2021-01-14 23:46 UTC
The unofficial guide is written in the original PR of the feature

https://github.com/nemtech/symbol-bootstrap/pull/92

We would need to put a nicer version of this doc in the official docs. 

This is for setup using bootstrap. The manual setup would be a bit more complicated.

**Comment by segfaultxavi** [comment] 2021-01-15 09:09
Duplicate of #550, will add this info to that issue.

**Closed by segfaultxavi** 2021-01-15 09:09 UTC
Labels: enhancement
