### ISSUE TITLE
Correction to the "Check that the balance on your NIS1 account was at least 2 XEM at the time of the snapshot."

### ISSUE THREAD

**Issue by Digimon-pl** [nemtech/symbol-docs#665] opened 2021-06-06 10:20 UTC
**Is your proposal related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Guys, in this doc describing the post-launch opt-in, in Troubleshooting section it is not clear what you mean by "Check that the balance on your NIS1 account was at least 2 XEM at the time of the snapshot".
As far as I have learnt from the Support, you need to have at least 2 XEM now at your account, from which the snapshot was taken. So maybe it would be better to have it as "Check that the balance on your NIS1 snapshot account is at least 2 XEM". Or if both are true "Check that the balance on your NIS1 account was at least 2 XEM at the time of the snapshot and it still is at least 2 XEM"

**Comment by segfaultxavi** [comment] 2021-06-07 07:25
The docs describe the intended behavior. Unfortunately a bug in the Wallet checks the current balance instead of the balance at the snapshot. This is about to be fixed in the next Wallet release so I will not change the docs.

Thanks for reporting, though!

**Closed by segfaultxavi** 2021-06-07 07:25 UTC
Labels: enhancement
